### ISSUE TITLE
Fix section schema

### ISSUE THREAD

**Issue by noahbkim** [mbhs/silverchips#10]
It will probably be easier to store Sections by an absolute path model.

**Comment by singerng** [comment]
How should Sections be organized? Currently, each Section simply maintains a pointer to the parent Section. There are two problems with this approach:

1. It's hard to get all the descendants of a Section, which we need to display the top stories in that Section.
2. There's no obvious way to store a fixed order among the children of any given Sections, or among the various root Sections, which we probably want when we display them (non-alphabetical).
