### ISSUE TITLE
Images are not included in fixtures, some are inconsistent

### ISSUE THREAD

**Issue by noahbkim** [mbhs/silverchips#31]
The `cleaned.json` fixtures simply omit models missing an author, which means stories with embeds are going to 404 on some images. Also, the actual image files are not available, so a way to deal with this needs to be devised.

**Comment by singerng** [comment]
Images are gigantic, so I'm not planning to include them in the fixtures. However, we should have a nice way for it to fail on embedding content without 404ing.
